apiVersion: v1
kind: Service
metadata:
  name: life-sports-discovery-management
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: life-sports-discovery-management