apiVersion: v1
kind: Service
metadata:
  name: life-sports-discovery-management
spec:
  type: LoadBalancer
  ports:
  - port: 8761
    protocol: TCP
  clusterIP: 10.104.34.38
  selector:
    run: life-sports-discovery-management